# Generated by Django 3.1 on 2021-02-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='information',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
